config/routes.rb
Rails.application.routes.draw do
  resources :offers, only: [:index]

  root 'offers#index'
  match "*path", to: 'application#routing_error', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer

  # This used to allow using validates method.
  include ActiveModel::Validations

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  # Validates all the given params
  # Should be valid URL and should be present.
  validates :hotel_url, :image_url, presence: true, format: /\Ahttps?:\/\/[[:alnum:]](?:-?[[:alnum:]])*(?:\.(?:[[:alnum:]](?:-?[[:alnum:]])*))+(?:\/.*|\z)/
  validates :hotel_name, :hotel_destination, :hotel_description, :currency, presence: true
  validates :booked_people_count, :viewing_people_count, :original_price,
    :average_price, numericality: { greater_than_or_equal_to: 0 }

  attr_accessor :image_url, :hotel_name, :hotel_url, :hotel_destination,
    :hotel_description, :booked_people_count, :viewing_people_count,
    :currency, :original_price, :average_price

  def self.get_deals params
    # Call the Hotel service to return all the given deals
    query_params = params.get_query_params
    deals = Services::HotelService.get_deals(query_params)
    deals_arr = []
    if deals.present?
      # Get all the given deals and validate their data.
      deals.each do |deal|

        offer = Offer.new
        offer.image_url = deal.try(:[],'hotelInfo').try(:[],'hotelImageUrl')
        offer.hotel_name = deal.try(:[],'hotelInfo').try(:[],'hotelName')
        offer.hotel_url =  URI.decode(deal.try(:[],'hotelUrls').try(:[],'hotelInfositeUrl'))
        offer.hotel_destination = deal.try(:[],'hotelInfo').try(:[],'hotelLongDestination')
        offer.hotel_description = deal.try(:[],'hotelInfo').try(:[],'description')
        offer.booked_people_count = deal.try(:[],'hotelUrgencyInfo').try(:[],'numberOfPeopleBooked')
        offer.viewing_people_count = deal.try(:[],'hotelUrgencyInfo').try(:[],'numberOfPeopleViewing')
        offer.currency = deal.try(:[],'hotelPricingInfo').try(:[],'currency')
        offer.original_price = deal.try(:[],'hotelPricingInfo').try(:[],'originalPricePerNight')
        offer.average_price = deal.try(:[],'hotelPricingInfo').try(:[],'averagePriceValue')

        deals_arr.append(offer) if offer.valid?
      end # End loop
    end # End if
    deals_arr
  end

end

app/models/query_params.rb
class QueryParams

  # This used to allow using validates method.
  include ActiveModel::Validations

  # Validates all the given params
  validates :region_id, :length_of_stay, :max_star_rating, :min_star_rating,
    numericality: { greater_than: 0 }, allow_blank: true

  validate do
    if max_star_rating.present? && min_star_rating.present? && max_star_rating < min_star_rating
      errors.add(:max_star_rating, 'must be greater than Min Star Rating')
    end
  end

  validate do
    if max_start_date.present?
      if (QueryParams.invalid_date?(max_start_date))
        errors.add(:max_start_date, 'is not a valid date')
      end
    end
  end

  validate do
    if min_start_date.present?
      if (QueryParams.invalid_date?(min_start_date))
        errors.add(:min_start_date, 'is not a valid date')
      end
    end
  end

  validate do
    if max_start_date.present? && min_start_date.present? && max_start_date < min_start_date
      errors.add(:max_start_date, 'must be greater than Min Trip Start Date')
    end
  end

  # attr_accessor method is used to create setter and getter
  # methods to all the given attributes
  # Ex: for the region_id attribute, the following two methods will be created:

  # Getter Method
  # def region_id
  #   @region_id
  # end

  # Setter Method
  # def region_id= value
  #   @region_id = value
  # end

  attr_accessor :destination_name, :region_id, :min_start_date, :max_start_date,
    :min_star_rating, :max_star_rating, :length_of_stay

  def get_query_params
    # Start with empty string and add params only if they exist
    # Self refers to the current object that is call the method.
    # Object that is being created in the controller.

    # self.destination_name.present? checks if the the @destination_name attribute
    # contains value or not.
    query = ""
    query += "&destinationName=#{self.destination_name}"  if self.destination_name.present?
    query += "&regionIds=#{self.region_id}" if self.region_id.present?
    query += "&minTripStartDate=#{self.min_start_date}"  if self.min_start_date.present?
    query += "&maxTripStartDate=#{self.max_start_date}"  if self.max_start_date.present?
    query += "&minStarRating=#{self.min_star_rating}"  if self.min_star_rating.present?
    query += "&maxStarRating=#{self.max_star_rating}"  if self.max_star_rating.present?
    query += "&lengthOfStay=#{self.length_of_stay}"  if self.length_of_stay.present?

    # No need to use return because in ruby by default the last executed
    # statment wil be returned without using the return.
    query
  end

  private
    def self.invalid_date? date
      (DateTime.parse(date) rescue ArgumentError) == ArgumentError
    end
end

app/models/services/hotel_service.rb
module Services
  module HotelService
    include HTTParty

    # Read offer_service URL from configuration file services.yml
    base_uri Rails.application.config_for(:services)["offer_service"]

    class << self
      def get_deals query
        begin
          response = get('/', {query: query}).parsed_response
          return response['offers']['Hotel']
        rescue
          return nil
        end
      end
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from ActionController::RoutingError, with: :render_not_found
  rescue_from ActionController::UnknownController, with: :render_not_found

  def routing_error
    raise ActionController::RoutingError.new "No route matches [#{request.method}] \"#{request.path}\""
  end

  protected
    def render_not_found
      render "shared/404", status: :not_found
    end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    # This will create an object that contains the given params
    # Ex: @region_id=$value

    # In Ruby everything is an object so to create new object
    # we need to call the class method new
    @offer_params = QueryParams.new
    allowed_params = query_params

    @offer_params.destination_name = allowed_params[:destination_name]
    @offer_params.region_id = allowed_params[:region_id]
    @offer_params.min_start_date = allowed_params[:min_start_date]
    @offer_params.max_start_date = allowed_params[:max_start_date]
    @offer_params.min_star_rating = allowed_params[:min_star_rating]
    @offer_params.max_star_rating = allowed_params[:max_star_rating]
    @offer_params.length_of_stay = allowed_params[:length_of_stay]

    # We need to run validations to make sure that data is valid
    # This will run all the validations in the Offer class.
    @deals = nil
    if @offer_params.valid?
      @deals = Offer.get_deals(@offer_params)
    end
  end

  private
    # Controller will accept the following params only, and if we need to
    # use extra params to the query string we need to add them to this method.
    def query_params
      params.permit(:destination_name, :region_id, :min_start_date, :max_start_date,
        :min_star_rating, :max_star_rating, :length_of_stay)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>Fattesh.com: search & find best hotel deals</title>
      <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
      <![endif]-->
      <%= stylesheet_link_tag    "application", :media => "all" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="span9"><%= yield %></div>
      </div>
    </div>
  </body>
</html>

app/views/offers/index.html.erb
<!-- Search Query Params -->
<nav class="navbar navbar-default">
    <h1 style="text-align: center; color: #337ab7;"> Hotel search </h1>
    <%= form_for(offers_path, method: "get", id: "search-form") do %>
      <br/><br/>

      <div class='col-md-5'>
        <%= text_field_tag :destination_name, params[:destination_name], placeholder: "  Destination Name"%><br/><br/>
      </div>

      <div class='col-md-5'>
        <%= number_field_tag :region_id, params[:region_id], placeholder: "  Region ID", min: 1%><br/><br/>
      </div>

      <div class='col-md-5'>
        <%= number_field_tag :min_star_rating, params[:min_star_rating], placeholder: "  Min Star Rating", min: 1%><br/><br/>
      </div>

       <div class='col-md-5'>
         <%= number_field_tag :max_star_rating, params[:max_star_rating], placeholder: "  Max Star Rating", min: 1%><br/><br/>
      </div>

      <div class='col-md-5'>
        <div class='input-group date' id='datetimepicker1'>
            <%= text_field_tag :min_start_date, params[:min_start_date], placeholder:
            'Min Trip Start Date', :class => 'form-control' %>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div><br/><br/>
      </div>

      <div class='col-md-5'>
        <div class='input-group date' id='datetimepicker2'>
             <%= text_field_tag :max_start_date, params[:max_start_date], placeholder:
            'Max Trip Start Date', :class => 'form-control' %>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div><br/></br>
      </div>

      <div class='col-md-5'>
        <%= submit_tag("Search", { :name => nil ,:align => "center", :class=>"btn btn-primary" })%>
        <%= submit_tag("Clear", { :name => 'reset', :type => "reset", :class=>"btn btn-primary"}) %>
         <br/></br>
      </div>
    <% end %>
  </div>
</nav>

<!-- Hotels Info-->
<% if @deals.present? %>
  <% @deals.each do |deal| %>
    <div class="container" style="margin-top:120px;">
      <div class="row">
        <!-- Product Info-->
        <div class="col-xs-12 col-sm-6">
          <h3> <%= deal.hotel_name %></h3>
          <h3> <%= deal.hotel_destination %></h3>

          <%= link_to(image_tag(deal.image_url, alt: deal.hotel_name, style: "width:300px; height:150px;", :class => "img-responsive product-image-large"), deal.hotel_url, target: "_blank").html_safe%>
        </div>

        <div class="col-xs-12 col-sm-6">
          <div class="well row">
            <div class="input-group", style="text-align: center; color: #337ab7;">
                <%= deal.booked_people_count %> of pepole booked this hotel
            </div>

            <div class="input-group", style="text-align: center; color: #337ab7">
                <%= deal.viewing_people_count %> of pepole viewed this hotel
            </div>

            <div class="input-group">
              Was <span style="text-decoration: line-through; color: #337ab7;"><%= deal.currency %><%= deal.original_price%> </span>  Now
              <span style="color: #337ab7;"> <%= deal.currency %><%= deal.average_price%>
            </div>
          </div>

          <h4>Description</h4>
          <p> <%= deal.hotel_description %></p>

          <div class="btn-group" role="group" aria-label="..." style="margin-bottom:10px;">
              <a href="<%= deal.hotel_url %>"><button type="button" class="btn btn-primary"><span class="fa fa-close"></span>&nbsp;View Deal</button></a>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% else %>

  <!-- Show error message if any -->
  <nav class="navbar navbar-default">
    <div class="container"> <br/>
      <% if @offer_params.errors.any? %>
          <h4><%= pluralize(@offer_params.errors.count, "error") %> prohibited this search from being continued:</h4>
          <% @offer_params.errors.full_messages.each do |message| %>
            <p style="color: #337ab7;"> <%= message %> </p>
          <% end %>
      <% else %>
        <p style="font-size: 1.2em; font-weight: normal; color: #337ab7">
            No Data avaliable with the given search
        </p>
      <% end %>
        <div class="btn-group" role="group" style="margin-bottom:10px;">
          <a href="<%= offers_path %>">
            <button type="button" class="btn btn-primary"><span class="fa fa-close"></span>&nbsp;Back to all deals</button></br>
          </a>
        </div>
    </div>
  </nav>
<% end %>

<script type="text/javascript">
  $(function () {
    $('#datetimepicker1').datetimepicker({
      format: 'l',
      format: 'YYYY-MM-DD'
    });
    $('#datetimepicker2').datetimepicker({
        useCurrent: false,
        format: 'l',
        format:'YYYY-MM-DD'
    });
    $("#datetimepicker1").on("dp.change", function (e) {
        $('#datetimepicker2').data("DateTimePicker").minDate(e.date);
    });
    $("#datetimepicker2").on("dp.change", function (e) {
        $('#datetimepicker1').data("DateTimePicker").maxDate(e.date);
    });
  });
</script>

app/views/shared/404.html.erb
<style>
  body {
    background-image:url('https://speckycdn-sdm.netdna-ssl.com/wp-content/uploads/2010/03/four-oh-four_08.jpg');
    background-repeat: no-repeat;
    background-position: center center;
    background-attachment: fixed;
  }
</style>


<head>
  <title>Page Not Found Fattesh.com</title>
</head>

<body></body>